#!/bin/bash

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"

ARPINGBIN=$(which arping 2>/dev/null)
if [ -z "${ARPINGBIN}" ];
then
  echo "arping NOT FOUND"
  exit 3
fi

while getopts 't:' OPT; do
  case $OPT in
    t)  TIMEOUT_ARPING=$OPTARG;;
  esac
done

shift $(($OPTIND - 1))

TIMEOUT_ARPING=${TIMEOUT_ARPING-5}

if [ -z "$1" ];
then
  echo "usage: $0 [ -t <timeout>] <IP>"
  exit 3
fi

RECEIVED_COUNT=$(sudo $ARPINGBIN -D $1 -w $TIMEOUT_ARPING | grep Received | tail -n1 | awk '{ print $2 }')

LOCAL_IP_COUNT=$(ip a | grep -Ec "\b$1\b" 2>/dev/null)

if [ "${LOCAL_IP_COUNT}" -eq 1 ];
then
  if [ "${RECEIVED_COUNT}" -eq 0 ];
  then
    echo "OK - $1 - ${RECEIVED}|received=${RECEIVED_COUNT}"
    exit 0
  else
    echo "CRITICAL - duplicated IP detected - $1 - ${RECEIVED}|received=${RECEIVED_COUNT}"
    exit 2
  fi
else
  if [ "${RECEIVED_COUNT}" -le 1 ];
  then
    echo "OK - $1 - ${RECEIVED}|received=${RECEIVED_COUNT}"
    exit 0
  else
    echo "CRITICAL - duplicated IP detected - $1 - ${RECEIVED}|received=${RECEIVED_COUNT}"
    exit 2
  fi
fi

