#!/bin/bash

SI=$(vmstat 1 3 | tail -n 1 | awk '{print $7}')
SO=$(vmstat 1 3 | tail -n 1 | awk '{print $8}')

if [ -z "$SO" ];
then
        echo UNKNOWN
        exit 3
fi

if [ -z "$SI" ];
then
	echo UNKNOWN
	exit 3
fi

echo "Swaping - Swap IN: $SI Swap OUT: $SO|si=$SI; so=$SO; "

if [ $SI -gt 0 ];
then
	exit 1
fi

if [ $SO -gt 0 ];
then
        exit 1
fi

exit 0

