#!/bin/bash

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

PSQLBASEOPTS="-A -t -q --pset pager=off"

SOCKETPSQL=/var/run/postgresql/
USERNAME=postgres
DATABASE=postgres
PORTSQL=5432

while getopts 'h:d:U:e:p:' OPT; 
do
	case $OPT in
		d)  DATABASE="$OPTARG"
		;;
		U)  USERNAME="$OPTARG"
		;;
		e)  EXECCMD="$OPTARG"
		;;
		h)  SOCKETPSQL="$OPTARG"
		;;
		p)  PORTSQL="$OPTARG"
		;;
		*)  WTF="yes"
		;;
	esac
done

shift $(($OPTIND - 1))

if [ -n "$WTF" ] || [ -n "$JELP" ];
then
	echo "usage: $0 -d <DATABASE> [OPTIONS]"
	echo -e "\t-d\t\tdatabase name to connect to (default: $USER)"
	echo -e "\t-U\t\tdatabase user name (default: $USER)"
	echo -e "\t-h\t\tdatabase server host or socket directory (default: /var/run/postgresql)"
	echo -e "\t-p\t\tdatabase server port (default: 5432)"
	echo -e "\t-e\t\tcommand to run (use %t for table)"
	exit 1
fi

PSQLBIN=$(which psql)

if [ -z "$PSQLBIN" ];
then
	echo "unable to find psql"
	exit 1
fi

if [ -z "$EXECCMD" ];
then
	$PSQLBIN -h "$SOCKETPSQL" -p "$PORTSQL" -U "$USERNAME" -d "$DATABASE" $PSQLBASEOPTS -c "select table_name from information_schema.tables where table_type='BASE TABLE';"
else
	$PSQLBIN -h "$SOCKETPSQL" -p "$PORTSQL" -U "$USERNAME" -d "$DATABASE" $PSQLBASEOPTS -c "select table_name from information_schema.tables where table_type='BASE TABLE';" | xargs -I %t echo "$EXECCMD" | $PSQLBIN -h "$SOCKETPSQL" -p "$PORTSQL" -U "$USERNAME" -d "$DATABASE" $PSQLBASEOPTS
fi


